function Hd = lpf10fir(Fs, Fpass, Fstop, atten )
%LPF10FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 09-Jun-2016 09:39:10

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
%Fs  is the Sampling Frequency
% Fpass  Passband Frequency
% Fstop  Stopband Frequency

Dpass = 0.057501127785;  % Passband Ripple
Dstop = 10^(-atten/20);          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);
fprintf('LPF length = %d \n', N);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
